USE smart_home;

DROP PROCEDURE IF EXISTS getSensorHistory;
DELIMITER $$
CREATE PROCEDURE getSensorHistory(
	IN MA_CB VARCHAR(20)
)
BEGIN
    drop table if exists result;
    create table result(
		THOI_GIAN DATETIME,
        GIA_TRI FLOAT DEFAULT NULL,
        TRANG_THAI BOOL DEFAULT NULL,
		NGUONG_TREN FLOAT DEFAULT NULL,
		NGUONG_DUOI FLOAT DEFAULT NULL,
        TEN VARCHAR(255) DEFAULT NULL
    );
    insert into result(THOI_GIAN,GIA_TRI) select THOI_GIAN,GIA_TRI from DU_LIEU_CAM_BIEN where DU_LIEU_CAM_BIEN.MA_CB=MA_CB;
    insert into result(THOI_GIAN,TRANG_THAI,NGUONG_TREN,NGUONG_DUOI,TEN) select THOI_GIAN,TRANG_THAI,NGUONG_TREN,NGUONG_DUOI,TEN from THIET_LAP_CAM_BIEN join USER on THIET_LAP_CAM_BIEN.MA_USER=USER.MA_USER where THIET_LAP_CAM_BIEN.MA_CB=MA_CB;
    select * from result order by THOI_GIAN desc;
END $$
DELIMITER ;

DROP PROCEDURE IF EXISTS getDeviceHistory;
DELIMITER $$
CREATE PROCEDURE getDeviceHistory(
	IN MA_TB VARCHAR(20)
)
BEGIN
    drop table if exists result;
    create table result(
		THOI_GIAN DATETIME,
        GIA_TRI FLOAT DEFAULT NULL,
        TRANG_THAI BOOL DEFAULT NULL,
		TU_DONG BOOL DEFAULT NULL,
        TEN VARCHAR(255) DEFAULT NULL
    );
    insert into result(THOI_GIAN,GIA_TRI) select THOI_GIAN,GIA_TRI from DU_LIEU_THIET_BI where DU_LIEU_THIET_BI.MA_TB=MA_TB;
    insert into result(THOI_GIAN,TRANG_THAI,TU_DONG,TEN,GIA_TRI) select THOI_GIAN,TRANG_THAI,TU_DONG,TEN,GIA_TRI from THIET_LAP_THIET_BI join USER on THIET_LAP_THIET_BI.MA_USER=USER.MA_USER where THIET_LAP_THIET_BI.MA_TB=MA_TB;
    select * from result order by THOI_GIAN desc;
END $$
DELIMITER ;